/*
 * main.h
 *
 *  Created on: Nov 19, 2023
 *      Author: ahadz
 */

#ifndef MAIN_H_
#define MAIN_H_

#include <stdint.h>
#include "stm32f746xx.h"

#define LD2_ON              GPIOB->BSRR |= GPIO_BSRR_BS7;
#define LD2_OFF             GPIOB->BSRR |= GPIO_BSRR_BR7;
#define PA4                 (1<<4)
#define BUTTON_PRESSED      GPIOA->IDR & PA4
#define LD2_TOGGLE          GPIOB->ODR ^= GPIO_ODR_OD7

void LD2_CONF(void);
void BUTTON_CONF(void);
void Delay(void);
void BUTTON_INT_CONF(void);

void LD2_CONF(void){
	//GPIO PORT B CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	//OUTPUT
	GPIOB->MODER |= GPIO_MODER_MODER7_0;
	GPIOB->MODER &= ~(GPIO_MODER_MODER7_1);
	//OUTPUT TYPE - PUSH PULL
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT7);
	//OUTPUT SPEED VERY LOW
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEEDR7);
	//NO PULL UP, NO PULL DOWN
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR7);
}

void Delay(void){
	uint32_t time;
	for(time = 0; time < 99999; time++){}
}

void BUTTON_CONF(void){
	//GPIO PORT B CLOCK ENABLE
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	//INPUT
	GPIOA->MODER &= ~(GPIO_MODER_MODER4);
	//PULL UP
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR4_0;
}

void BUTTON_INT_CONF(void){
	//SYSCFG ENABLE
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	//EXTERNAL INT CONFIG IN SYSCFG
	SYSCFG->EXTICR[2] = 0;
	//EXTI MASK DISABLE
	EXTI->IMR |= EXTI_IMR_IM4;
	//INT ON FALLING EDGE
	EXTI->RTSR |= EXTI_FTSR_TR4;
	EXTI->FTSR &= ~(EXTI_RTSR_TR4);
	//SET PRIORITY
	NVIC_SetPriority (EXTI4_IRQn, 2);
	//ENABLE INT
	NVIC_EnableIRQ (EXTI4_IRQn);
}


#endif /* MAIN_H_ */
