/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"


// PB7 - LD2
// PA4 - BUTTON

//INT HANDLER FOR BUTTON
void EXTI4_IRQHandler(void);

int main(void)
{
    LD2_CONF();
	BUTTON_CONF();
	BUTTON_INT_CONF();

	LD2_OFF;

	while(1){

	}
}

void EXTI4_IRQHandler(void){
	while(BUTTON_PRESSED){
		//WAIT
	}
	Delay();
	LD2_TOGGLE;
	BUTTON_INT_CLEAR;
}
